### ISSUE TITLE
no release available with updated dependencies

### ISSUE THREAD

**Issue by fredwillmore** [CGamesPlay/haml_user_tags#7]
Hi team,
I noticed you have a commit (60dc851) to address some updated dependencies (particularly around Erubis deprecation in Rails 5.1), but there is no release available on rubygems.org that includes that commit. I would like to use with Rails > 5.1

**Comment by CGamesPlay** [comment]
Hi @fredwillmore, I will try to get a new release of this software this week. In the mean time, you can reference the specific version directly:

```ruby
```

**Comment by CGamesPlay** [comment]
I've gone ahead and pushed an updated version to include the latest commits. Note however that in my testing I discovered that the library is incompatible with many of the latest versions of packages and I wasn't able to install a working set of dependencies to even get the test suite running. Please see the new note in the [README](https://github.com/CGamesPlay/haml_user_tags) for more info.
